stages:
  - deploy

deploy_test:
  stage: deploy
  image: debian:jessie
  only: 
    - test
  script:
    - apt-get -u update
    - apt-get -y install curl zip
    - sed -i "s|#WHATSNEW#|$WHATSNEW|" js/app.js
    - sed -i "s|#VERSION#|$VERSION|" js/app.js
    - sed -i "s|#DOWNLOAD#|$DOWNLOAD|" js/app.js
    - curl -T whatsnew.html $FTPSITE/janban-test/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - mv kanban.html index.html
    - curl -T index.html $FTPSITE/janban-test/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T janban-icon-512.jpg $FTPSITE/janban-test/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T lib/angular.js $FTPSITE/janban-test/lib/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T lib/angular.min.js $FTPSITE/janban-test/lib/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T lib/bootstrap.min.js $FTPSITE/janban-test/lib/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T lib/deep-diff-0.3.8.min.js $FTPSITE/janban-test/lib/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T lib/checklist-model.js $FTPSITE/janban-test/lib/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T lib/jquery.min.js $FTPSITE/janban-test/lib/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T lib/jquery-ui.min.js $FTPSITE/janban-test/lib/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T lib/minify.json.js $FTPSITE/janban-test/lib/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T lib/moment.min.js $FTPSITE/janban-test/lib/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T lib/sortable.js $FTPSITE/janban-test/lib/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T lib/sortable.min.js $FTPSITE/janban-test/lib/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T js/app.js $FTPSITE/janban-test/js/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T js/exchange.js $FTPSITE/janban-test/js/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T js/version.js $FTPSITE/janban-test/js/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T css/bootstrap.min.css $FTPSITE/janban-test/css/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T css/taskboard.css $FTPSITE/janban-test/css/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T fonts/glyphicons-halflings-regular.eot $FTPSITE/janban-test/fonts/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T fonts/glyphicons-halflings-regular.svg $FTPSITE/janban-test/fonts/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T fonts/glyphicons-halflings-regular.ttf $FTPSITE/janban-test/fonts/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T fonts/glyphicons-halflings-regular.woff $FTPSITE/janban-test/fonts/ --user $FTPUSERJANWARE:$FTPPWDJANWARE
    - curl -T fonts/glyphicons-halflings-regular.woff2 $FTPSITE/janban-test/fonts/ --user $FTPUSERJANWARE:$FTPPWDJANWARE

deploy_next:
  stage: deploy
  image: debian:jessie
  only: 
    - next
  script:
    - apt-get -u update
    - apt-get -y install curl zip
    - sed -i "s|#WHATSNEW#|$WHATSNEW|" js/app.js
    - sed -i "s|#VERSION#|$VERSION|" js/app.js
    - sed -i "s|#DOWNLOAD#|$DOWNLOAD|" js/app.js
    - curl -T whatsnew.html $FTPSITE/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - mv kanban.html index.html
    - zip -r  janban-next.zip *
    - curl -T janban-next.zip $FTPSITE --user $FTPUSER:$FTPPWD
    - curl -T index.html $FTPSITE --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T janban-icon-512.jpg $FTPSITE --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T lib/angular.js $FTPSITE/lib/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T lib/angular.min.js $FTPSITE/lib/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T lib/bootstrap.min.js $FTPSITE/lib/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T lib/deep-diff-0.3.8.min.js $FTPSITE/lib/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T lib/checklist-model.js $FTPSITE/lib/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T lib/jquery.min.js $FTPSITE/lib/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T lib/jquery-ui.min.js $FTPSITE/lib/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T lib/minify.json.js $FTPSITE/lib/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T lib/moment.min.js $FTPSITE/lib/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T lib/sortable.js $FTPSITE/lib/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T lib/sortable.min.js $FTPSITE/lib/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T js/app.js $FTPSITE/js/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T js/exchange.js $FTPSITE/js/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T js/version.js $FTPSITE/js/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T css/bootstrap.min.css $FTPSITE/css/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T css/taskboard.css $FTPSITE/css/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T fonts/glyphicons-halflings-regular.eot $FTPSITE/fonts/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T fonts/glyphicons-halflings-regular.svg $FTPSITE/fonts/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T fonts/glyphicons-halflings-regular.ttf $FTPSITE/fonts/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T fonts/glyphicons-halflings-regular.woff $FTPSITE/fonts/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T fonts/glyphicons-halflings-regular.woff2 $FTPSITE/fonts/ --user $FTPUSERNEXT:$FTPPWDNEXT
    - curl -T install.cmd $FTPSITE --user $FTPUSERNEXT:$FTPPWDNEXT

deploy:
  stage: deploy
  image: debian:jessie
  only:
    - main
  script:
    - apt-get -u update 
    - apt-get -y install zip unzip curl
    - curl -O $FTPSITE/janban.zip  --user $FTPUSER:$FTPPWD
    - curl -O $FTPSITE/version.txt  --user $FTPUSER:$FTPPWD
    - export xx=`cat version.txt`
    - if curl -O $FTPSITE/janban.$xx.zip --user $FTPUSER:$FTPPWD; then echo found; else echo not found; fi
    - if [ -f janban.$xx.zip ]; then echo no upload needed; else mv janban.zip janban.$xx.zip && curl -T janban.$xx.zip $FTPSITE --user $FTPUSER:$FTPPWD; fi
    - rm janban.$xx.zip
    - rm version.txt
    - sed -i "s|#WHATSNEW#|$WHATSNEW|" js/app.js
    - sed -i "s|#VERSION#|$VERSION|" js/app.js
    - sed -i "s|#DOWNLOAD#|$DOWNLOAD|" js/app.js
    - sed 's/";//g' js/version.js > version.txt1
    - sed 's/const VERSION = "//g' version.txt1 > version.txt
    - curl -T version.txt $FTPSITE --user $FTPUSER:$FTPPWD
    - curl -T whatsnew.html $FTPSITE --user $FTPUSER:$FTPPWD
    - curl -T upgrade.html $FTPSITE --user $FTPUSER:$FTPPWD
    - rm version.txt
    - rm version.txt1
    - rm whatsnew.html
    - rm upgrade.html
    - zip -r  install.zip install.cmd
    - curl -T install.zip $FTPSITE --user $FTPUSER:$FTPPWD
    - rm install.zip
    - zip -r  janban.zip *
    - curl -T janban.zip $FTPSITE --user $FTPUSER:$FTPPWD
    - mv kanban.html index.html
    - curl -T index.html $FTPSITE --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T janban-icon-512.jpg $FTPSITE --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - ls lib
    - curl -T lib/angular.js $FTPSITE/lib/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T lib/angular.min.js $FTPSITE/lib/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T lib/bootstrap.min.js $FTPSITE/lib/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T lib/deep-diff-0.3.8.min.js $FTPSITE/lib/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T lib/checklist-model.js $FTPSITE/lib/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T lib/jquery.min.js $FTPSITE/lib/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T lib/jquery-ui.min.js $FTPSITE/lib/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T lib/minify.json.js $FTPSITE/lib/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T lib/moment.min.js $FTPSITE/lib/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T lib/sortable.js $FTPSITE/lib/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T lib/sortable.min.js $FTPSITE/lib/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T js/app.js $FTPSITE/js/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T js/exchange.js $FTPSITE/js/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T js/version.js $FTPSITE/js/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T css/bootstrap.min.css $FTPSITE/css/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T css/taskboard.css $FTPSITE/css/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T fonts/glyphicons-halflings-regular.eot $FTPSITE/fonts/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T fonts/glyphicons-halflings-regular.svg $FTPSITE/fonts/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T fonts/glyphicons-halflings-regular.ttf $FTPSITE/fonts/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T fonts/glyphicons-halflings-regular.woff $FTPSITE/fonts/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T fonts/glyphicons-halflings-regular.woff2 $FTPSITE/fonts/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T install.cmd $FTPSITE --user $FTPUSERJANBAN:$FTPPWDJANBAN
