stages:
  - deploy

deploy:
  stage: deploy
  image: debian:jessie
  only:
    - main
  script:
    - apt-get -u update 
    - apt-get -y install zip unzip curl
    - curl -O $FTPSITE/janban.zip  --user $FTPUSER:$FTPPWD
    - curl -O $FTPSITE/version.txt  --user $FTPUSER:$FTPPWD
    - export xx=`cat version.txt`
    - if curl -O $FTPSITE/janban.$xx.zip --user $FTPUSER:$FTPPWD; then echo found; else echo not found; fi
    - if [ -f janban.$xx.zip ]; then echo no upload needed; else mv janban.zip janban.$xx.zip && curl -T janban.$xx.zip $FTPSITE --user $FTPUSER:$FTPPWD; fi
    - rm janban.$xx.zip
    - rm version.txt
    - sed -i "s|#WHATSNEW#|$WHATSNEW|" js/app.js
    - sed -i "s|#VERSION#|$VERSION|" js/app.js
    - sed -i "s|#DOWNLOAD#|$DOWNLOAD|" js/app.js
    - sed 's/";//g' js/version.js > version.txt1
    - sed 's/const VERSION = "//g' version.txt1 > version.txt
    - curl -T "{upgrade.html,whatsnew.html,version.txt}" $FTPSITE --user $FTPUSER:$FTPPWD
    - rm version.txt
    - rm version.txt1
    - rm whatsnew.html
    - rm upgrade.html
    - zip -r  install.zip install.cmd
    - curl -T install.zip $FTPSITE --user $FTPUSER:$FTPPWD
    - rm install.zip
    - zip -r  janban.zip *
    - mv kanban.html index.html
    - curl -T "{install.cmd,janban-icon-512.jpg,index.html,janban.zip}" $FTPSITE --user $FTPUSER:$FTPPWD
    - curl -T "{lip/sortable.min.js,lip/sortable.js,lip/moment.min.js,lip/minify.json.js,lip/jquery-ui.min.js,lip/jquery.min.js,lip/checklist-model.js,lip/deep-diff-0.3.8.min.js,lip/bootstrap.min.js,lip/angular.min.js,lip/angular.js}" $FTPSITE/lip/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T "{js/version.js,js/exchange.js,js/app.js}" $FTPSITE/js/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T "{css/taskboard.css,css/bootstrap.min.css}" $FTPSITE/css/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
    - curl -T "{fonts/glyphicons-halflings-regular.woff2,fonts/glyphicons-halflings-regular.woff,fonts/glyphicons-halflings-regular.ttf,fonts/glyphicons-halflings-regular.svg,fonts/glyphicons-halflings-regular.eot}" $FTPSITE/fonts/ --user $FTPUSERJANBAN:$FTPPWDJANBAN
